const genres = [
    "acoustic pop",
    "adult standards",
    "african electronic",
    "afro dancehall",
    "afro r&b",
    "afrofuturism",
    "afrofuturismo brasileiro",
    "afropop",
    "afroswing",
    "album rock",
    "alt z",
    "alte",
    "alternative dance",
    "alternative hip hop",
    "alternative pop rock",
    "alternative r&b",
    "alternative rock",
    "anadolu rock",
    "antilliaanse rap",
    "arab alternative",
    "arabic hip hop",
    "arkansas hip hop",
    "art pop",
    "art rock",
    "atl hip hop",
    "austindie",
    "australian indie",
    "australian pop",
    "australian psych",
    "azontobeats",
    "baltimore hip hop",
    "baroque pop",
    "bass trap",
    "baton rouge rap",
    "bay area indie",
    "bedroom pop",
    "bedroom soul",
    "belgian pop",
    "blues rock",
    "bossbeat",
    "brazilian hip hop",
    "brazilian rock",
    "brighton indie",
    "british soul",
    "brostep",
    "brutal death metal",
    "cali rap",
    "cambridgeshire indie",
    "canadian contemporary r&b",
    "canadian electropop",
    "canadian hip hop",
    "canadian pop",
    "canadian trap",
    "cante flamenco",
    "chicago indie",
    "chicago rap",
    "chilean indie",
    "chilean rock",
    "chill drill",
    "chill r&b",
    "classic rock",
    "classic uk pop",
    "commons",
    "complextro",
    "conscious hip hop",
    "contemporary r&b",
    "contemporary vocal jazz",
    "country rock",
    "cuban alternative",
    "dance pop",
    "dance rock",
    "dance-punk",
    "danish pop",
    "death metal",
    "deathgrind",
    "deep euro house",
    "deep house",
    "desi hip hop",
    "destroy techno",
    "detroit rock",
    "dfw rap",
    "disco",
    "disco house",
    "dmv rap",
    "dominican pop",
    "downtempo",
    "dreamo",
    "drill brasileiro",
    "drill francais",
    "dutch edm",
    "dutch hip hop",
    "dutch indie",
    "dutch r&b",
    "dutch rap pop",
    "east coast hip hop",
    "edm",
    "electra",
    "electro house",
    "electro-pop francais",
    "electronic trap",
    "electronica",
    "electronica chilena",
    "electropop",
    "emo rap",
    "emo rap italiano",
    "english indie rock",
    "epicore",
    "escape room",
    "etherpop",
    "experimental hip hop",
    "experimental r&b",
    "fado",
    "filter house",
    "flamenco",
    "folk rock",
    "french hip hop",
    "french indie folk",
    "french indie pop",
    "french indietronica",
    "french pop",
    "french techno",
    "funk",
    "funk bh",
    "funk carioca",
    "funk metal",
    "funk mtg",
    "funk ostentacao",
    "funk rock",
    "gaming edm",
    "gangster rap",
    "garage rock",
    "gauze pop",
    "german alternative rap",
    "german boom bap",
    "german cloud rap",
    "german dance",
    "german drill",
    "german hip hop",
    "german pop",
    "german r&b",
    "german trap",
    "german underground rap",
    "glam rock",
    "grave wave",
    "greek indie",
    "greek pop",
    "greek swing",
    "grime",
    "grime brasileiro",
    "grimewave",
    "grunge",
    "hamburg hip hop",
    "hard rock",
    "hardcore hip hop",
    "heartland rock",
    "high vibe",
    "hip hop",
    "hip hop cubano",
    "hip hop tuga",
    "hip pop",
    "horror synth",
    "house",
    "hyperpop",
    "icelandic indie",
    "icelandic rock",
    "indie folk",
    "indie game soundtrack",
    "indie hip hop",
    "indie jazz",
    "indie pop",
    "indie poptimism",
    "indie r&b",
    "indie rock",
    "indie rock italiano",
    "indie soul",
    "indie surf",
    "indietronica",
    "irish singer-songwriter",
    "italian indie pop",
    "japanese dance pop",
    "jazz catala",
    "jazz pop",
    "karadeniz turkuleri",
    "kentucky hip hop",
    "kizomba cabo-verdiana",
    "kora",
    "la indie",
    "la pop",
    "latin alternative",
    "latin hip hop",
    "lgbtq+ hip hop",
    "lo-fi beats",
    "lo-fi chill",
    "lo-fi cover",
    "lo-fi rap",
    "lo-fi vgm",
    "london rap",
    "lounge",
    "malian blues",
    "mallet",
    "mande pop",
    "manguebeat",
    "mellow gold",
    "melodic drill",
    "melodic rap",
    "memphis hip hop",
    "metropopolis",
    "middle east hip hop",
    "milan indie",
    "minneapolis indie",
    "minnesota hip hop",
    "modern alternative pop",
    "modern alternative rock",
    "modern blues",
    "modern blues rock",
    "modern hard rock",
    "modern indie pop",
    "modern reggae",
    "modern rock",
    "moroccan pop",
    "multidisciplinary",
    "musica capixaba",
    "musica goiana",
    "musica triste brasileira",
    "musique mandingue",
    "neo mellow",
    "neo r&b",
    "neo soul",
    "neo-synthpop",
    "new french touch",
    "new rave",
    "nigerian pop",
    "norrlandsk hip hop",
    "north carolina hip hop",
    "nouvelle chanson francaise",
    "nova mpb",
    "nuevo flamenco",
    "nyc pop",
    "nyc rap",
    "oakland hip hop",
    "ottawa indie",
    "permanent wave",
    "piano rock",
    "pittsburgh rap",
    "political hip hop",
    "pop",
    "pop chileno",
    "pop dance",
    "pop edm",
    "pop electronico",
    "pop lgbtq+ brasileira",
    "pop quebecois",
    "pop r&b",
    "pop rap",
    "pop rock",
    "pop soul",
    "pop urbaine",
    "portuguese pop",
    "post-teen pop",
    "progressive electro house",
    "progressive house",
    "progressive rock",
    "punk blues",
    "quiet storm",
    "r&b",
    "r&b brasileiro",
    "r&b italiano",
    "rap",
    "rap angolano",
    "rap baiano",
    "rap calme",
    "rap capixaba",
    "rap conscient",
    "rap francais",
    "rap francais nouvelle vague",
    "rap inde",
    "rap maroc",
    "rap politico",
    "rebel blues",
    "rhode island rap",
    "rochester mn indie",
    "rock",
    "roots rock",
    "russian alt pop",
    "russian electronic",
    "russian emo",
    "russian indie",
    "russian indie rock",
    "sad rap",
    "scam rap",
    "scandinavian r&b",
    "schweizer rap",
    "sheffield indie",
    "shimmer pop",
    "shiver pop",
    "singer-songwriter",
    "soft rock",
    "soul",
    "soundtrack",
    "southern hip hop",
    "stomp and holler",
    "surf punk",
    "swedish hip hop",
    "swedish pop",
    "syrian hip hop",
    "syrian pop",
    "technical death metal",
    "tennessee hip hop",
    "toronto rap",
    "trap",
    "trap catala",
    "trap queen",
    "trap soul",
    "traprun",
    "trip hop",
    "tropical house",
    "turkish instrumental",
    "turkish psych",
    "turkish rock",
    "uk alternative hip hop",
    "uk contemporary r&b",
    "uk drill",
    "uk hip hop",
    "uk pop",
    "underground hip hop",
    "urban contemporary",
    "vapor soul",
    "vapor trap",
    "vegas indie",
    "video game music",
    "viral pop",
    "viral rap",
    "vocal house",
    "weirdcore",
    "windsor on indie",
    "world",
    "yacht rock"
]